version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

    commands:
      - echo Executing Install Phase
      # Update libs
      - apt-get update
      # Headless Chrome
      - apt-get install -y fonts-liberation libasound2 libnspr4 libnss3 libx11-xcb1 xdg-utils libxss1 libappindicator1 libindicator7
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - dpkg -i google-chrome*.deb
    finally:
      - echo Executing Install finally
  pre_build:
    commands:
      - echo Executing Pre build Phase
      - npm install
    finally:
      - echo Executing Pre build finally
  build:
    commands:
      - echo Executing  build Phase
      - npm run build:ci
      - npm run test:ci
    finally:
      - echo Executing build finally 
  post_build:
    commands:
      - echo Executing Post build Phase
    finally:
      - echo Executing Post build finally 


artifacts:
  files:
    - '**/*.html'
    - '**/*.js'
    - '**/*.css'
    - '**/*.css'
  discard-paths: yes
  base-directory: 'dist/awsangular'